server:
  port: 8081

jwt:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

spring:
  profiles:
    active: dev
  application:
    name: auth-service
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true